// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwqT-V30glfWSTw8f7vjgC_vcD3KpPVB0',
    appId: '1:281914321358:web:019bde3ae2758e2cd2239f',
    messagingSenderId: '281914321358',
    projectId: 'monjardin-afae3',
    authDomain: 'monjardin-afae3.firebaseapp.com',
    storageBucket: 'monjardin-afae3.firebasestorage.app',
    measurementId: 'G-F0TMLQJ5RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1quNRfeCBkQ9raML324MiCprJpa7-Ous',
    appId: '1:281914321358:android:c1ac5366e8b93e04d2239f',
    messagingSenderId: '281914321358',
    projectId: 'monjardin-afae3',
    storageBucket: 'monjardin-afae3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsugCMgEsH7E486fK8Djz7v6EyMkmT4S0',
    appId: '1:281914321358:ios:d4c9732b4eb61f84d2239f',
    messagingSenderId: '281914321358',
    projectId: 'monjardin-afae3',
    storageBucket: 'monjardin-afae3.firebasestorage.app',
    iosBundleId: 'com.jardinapp.jardinapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsugCMgEsH7E486fK8Djz7v6EyMkmT4S0',
    appId: '1:281914321358:ios:d4c9732b4eb61f84d2239f',
    messagingSenderId: '281914321358',
    projectId: 'monjardin-afae3',
    storageBucket: 'monjardin-afae3.firebasestorage.app',
    iosBundleId: 'com.jardinapp.jardinapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwqT-V30glfWSTw8f7vjgC_vcD3KpPVB0',
    appId: '1:281914321358:web:fb7212c1f3419dedd2239f',
    messagingSenderId: '281914321358',
    projectId: 'monjardin-afae3',
    authDomain: 'monjardin-afae3.firebaseapp.com',
    storageBucket: 'monjardin-afae3.firebasestorage.app',
    measurementId: 'G-4PFEYMKNMC',
  );
}
