# ios/Podfile
platform :ios, '13.0'

# Emplacement du helper script de Flutter
flutter_install_all_ios_pods = File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), __FILE__)
require flutter_install_all_ios_pods

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.expand_path(File.join('..', 'Flutter'), __FILE__)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
